[package]
name = "worgen-rs"
version = "0.1.0"
authors = ["Nocthir <nocthir@proton.me>"]
edition = "2024"
license = "MIT OR Apache-2.0"
description = "An interactive 3D application for exploring immersive virtual environments."
repository = "https://github.com/nocthir/worgen-rs"

# Enable a small amount of optimization in the dev profile.
[profile.dev]
opt-level = 1

# Enable a large amount of optimization in the dev profile for dependencies.
[profile.dev.package."*"]
opt-level = 3

[dependencies]
bevy = "0.16.*"
